language: node_js
node_js:
  - 18.14.1
services:
  - mongodb
before_script:
  - sleep 15
  - mongo admin --eval 'db.createUser({user:"mongo",pwd:"mongo",roles:["readWrite"]});'
env:
  - MONGODB_URI=mongodb://mongo:mongo@localhost:27017/test?authSource=admin
script:
  - npm i --production
  - npm audit fix
  - npm run build
  - npm test
after_success:
  - bash <(curl -s https://codecov.io/bash)
